edutools_site/urls.py
from django.contrib import admin
from django.urls import path, include
from mkr import views
# from .settings import MEDIA_URL, MEDIA_ROOT
# from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('edutools_home.urls')),
    path('wlan-codes/', include('WLANCodesWebApp.urls')),
    path('wlan-codes/codeimport/', include('codeimport.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('booking/', include('buchungstool.urls')),
    path('userlist/', include('userlist.urls')),
    path('booking/devices/', include('devicelist.urls')),
    path('booking/settings/', include('buchungstool_settings.urls')),
    path('mkr/', include('mkr.urls')),
    path('qrcode_generator/', include('qrcode_generator.urls')),
    path('library_manager/', include('library_manager.urls')),
    path('appointment/', include('appointment.urls')),
    path('activity/', include('activity.urls')),
    path('educards/', include('eduCards.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('logo/<filename>', views.get_logo, name='get_logo'),
]

# urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

library_manager/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.inventory, name='inventory'),
    path('import/', views.book_import, name='book_import'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('new/', views.new, name='new'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('borrow/<int:id>/', views.borrow, name='borrow'),
    path('returnlist/', views.returnlist, name='returnlist'),
    path('return/<int:id>/', views.return_book, name='return_book'),
    path('manage_categories/', views.manage_categories, name='manage_categories'),
    path('new_category/', views.new_category, name='new_category'),
]

mkr/urls.py
from django.urls import path
from . import views
from .views import rate_limit_exceeded_view

urlpatterns = [
    path('', views.home, name='mkr_home'),
    path('karte/', views.karte, name='karte'),
    path('karte_bearbeiten/<int:id>', views.karte_bearbeiten, name='karte_bearbeiten'),
    path('download/<filename>', views.download, name='download'),
    path('lehrplanansicht', views.lehrplanansicht, name='lehrplanansicht'),
    path('images/<filename>', views.get_image, name='get_image'),
    path('rate-limit-exceeded/', rate_limit_exceeded_view, name='rate_limit_exceeded'),
]

library_manager/models.py
from django.db import models
from django.utils import timezone


class LibraryCategoryShelfmark(models.Model):
    category = models.CharField(max_length=50, unique=True)
    shelfmark = models.CharField(max_length=50, unique=True)

    def __str__(self):
        if not self.category:
            self.category = ""
        return self.category + '/' + self.shelfmark

    class Meta:
        ordering = ['category']

    @property
    def items_in_category(self):
        items = InventoryItem.objects.filter(category_shelfmark=self)
        return len(items)


class LibraryLocation(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        if not self.name:
            self.name = ""
        return self.name


class LibraryStatus(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        if not self.name:
            self.name = ""
        return self.name


class InventoryItem(models.Model):
    author = models.CharField(max_length=120)
    title = models.CharField(max_length=120)
    category_shelfmark = models.ForeignKey(LibraryCategoryShelfmark, on_delete=models.PROTECT)
    inventory_number = models.IntegerField(blank=True, unique=True)
    location = models.ForeignKey(LibraryLocation, on_delete=models.PROTECT)
    status = models.ForeignKey(LibraryStatus, on_delete=models.PROTECT)
    notes = models.TextField(max_length=10000, blank=True, null=True)

    @property
    def next_inventory_number(self):
        obj = InventoryItem.objects.all()
        if obj.count() == 0:
            return 1
        else:
            return obj.aggregate(models.Max('inventory_number'))['inventory_number__max'] + 1

    @property
    def borrowed(self):
        try:
            borrowed = LibraryBorrowedItem.objects.get(book=self)
        except LibraryBorrowedItem.DoesNotExist:
            borrowed = None
        return borrowed


class LibraryBorrowedItem(models.Model):
    first_name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    school_class = models.CharField(max_length=100)
    book = models.ForeignKey(InventoryItem, on_delete=models.PROTECT, blank=True)
    borrowing_date = models.DateField(blank=True)
    return_date = models.DateField(blank=True, null=True)

    @property
    def return_overdue(self):
        if self.return_date < timezone.now().date():
            diff = timezone.now().date() - self.return_date
            return diff.days
        else:
            return None

    class Meta:
        ordering = ['return_date']

library_manager/forms.py
from django.forms import ModelForm
from django import forms
from .models import InventoryItem, LibraryBorrowedItem, LibraryCategoryShelfmark


class InventoryItemForm(ModelForm):
    class Meta:
        model = InventoryItem
        fields = (
            'author',
            'title',
            'category_shelfmark',
            # 'status',
            'inventory_number',
            'notes',
        )
        labels = {
            'author': 'Autor:in',
            'title': 'Titel',
            'category_shelfmark': 'Bereich/Signatur',
            # 'status': 'Status',
            'inventory_number': 'Inventarnummer (automatisch)',
            'notes': 'Bemerkungen',
        }
        widgets = {
            'author': forms.TextInput(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'category_shelfmark': forms.Select(attrs={'class': 'form-select', 'style': 'width: 40%'}),
            # 'status': forms.Select(attrs={'class': 'form-select', 'style': 'width: 40%'}),
            'inventory_number': forms.TextInput(attrs={'class': 'form-control text-center', 'style': 'width: 100px'}),
            'notes': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
        }


class LibraryBorrowedItemsForm(ModelForm):
    class Meta:
        model = LibraryBorrowedItem
        fields = (
            'first_name',
            'surname',
            'school_class',
        )
        labels = {
            'first_name': 'Vorname',
            'surname': 'Nachname',
            'school_class': 'Klasse',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'surname': forms.TextInput(attrs={'class': 'form-control'}),
            'school_class': forms.TextInput(attrs={'class': 'form-control'}),
        }


class LibraryCategoryShelfmarkNewForm(ModelForm):
    class Meta:
        model = LibraryCategoryShelfmark
        fields = (
            'category',
            'shelfmark',
        )
        labels = {
            'category': 'Bereich',
            'shelfmark': 'Signatur',
        }
        widgets = {
            'category': forms.TextInput(attrs={'class': 'form-control'}),
            'shelfmark': forms.TextInput(attrs={'class': 'form-control'}),
        }

library_manager/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import InventoryItem, LibraryCategoryShelfmark, LibraryLocation, LibraryStatus, LibraryBorrowedItem
from .forms import InventoryItemForm, LibraryBorrowedItemsForm, LibraryCategoryShelfmarkNewForm
from django.utils import timezone
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.admin.views.decorators import staff_member_required


def is_library_admin(user):
    return user.is_staff or user.groups.filter(name='library_admin').exists()


def is_library_assistant(user):
    return user.groups.filter(name='library_assistant').exists()


@login_required
def inventory(request):
    if request.GET.get('location'):
        current_location = request.GET.get('location')
    else:
        # use first location as default
        current_location = LibraryLocation.objects.filter().first()
        if current_location:
            current_location = int(current_location.id)

    # Get objects for location
    library_items = InventoryItem.objects.filter(location=current_location)

    # Get locations for filter
    locations = LibraryLocation.objects.all()

    # Get status for filter
    status_items = LibraryStatus.objects.all()

    # Filter by category if specified
    if request.GET.get('filter_category'):
        if request.GET.get('filter_category') != "0":
            library_items = library_items.filter(category_shelfmark=request.GET.get('filter_category'))
        current_category = request.GET.get('filter_category')
    else:
        current_category = 0

    # Filter by status if specified
    if request.GET.get('filter_status'):
        if request.GET.get('filter_status') != "0":
            library_items = library_items.filter(status=request.GET.get('filter_status'))
        current_status = request.GET.get('filter_status')
    else:
        current_status = 0

    # Filter by text if specified
    current_text = ""
    if request.GET.get('filter_text'):
        library_items = library_items.filter(author__icontains=request.GET.get('filter_text')) | library_items.filter(title__icontains=request.GET.get('filter_text')) | library_items.filter(inventory_number__icontains=request.GET.get('filter_text'))
        current_text = request.GET.get('filter_text')

    item_count = None
    if not request.GET.get('show_all'):
        # Slice the QuerySet to get the first 100 items
        item_count = library_items.count()
        if item_count <= 100:
            item_count = None
        library_items = library_items[:100]

    category_items = LibraryCategoryShelfmark.objects.all()
    return render(request, 'library_inventory.html', {
        'library_items': library_items,
        'category_items': category_items,
        'current_category': int(current_category),
        'current_text': current_text,
        'item_count': item_count,
        'locations': locations,
        'current_location': current_location,
        'status_items': status_items,
        'current_status': int(current_status),
        'library_admin': is_library_admin(request.user),
        }
    )


@login_required
@user_passes_test(is_library_admin)
def edit(request, id):
    obj = InventoryItem.objects.get(id=id)

    if request.method == 'POST':
        f = InventoryItemForm(request.POST, instance=obj)
        if f.is_valid():
            inst = f.save(commit=False)
            if request.POST.get('lost'):
                current_status, created = LibraryStatus.objects.get_or_create(name="verschwunden")
                inst.status = current_status
            elif inst.status.name == "verschwunden":
                inst.status = LibraryStatus.objects.get(name="verfügbar")
            inst.save()
            filter_category = request.GET.get('filter_category', '0')
            filter_status = request.GET.get('filter_status', '0')
            filter_text = request.GET.get('filter_text', '')
            return redirect(f"{reverse('inventory')}?filter_category={filter_category}&filter_status={filter_status}&filter_text={filter_text}")
        else:
            return render(request, 'library_edit.html', {'form': f})

    f = InventoryItemForm(instance=obj)
    return render(request, 'library_edit.html', {'form': f})


@login_required
@user_passes_test(is_library_admin)
def new(request):
    if request.method == 'POST':
        f = InventoryItemForm(request.POST)
        if f.is_valid():
            inst = f.save(commit=False)
            inst.inventory_number = inst.next_inventory_number
            location_obj = LibraryLocation.objects.get(id=request.GET.get('location'))
            inst.location = location_obj
            current_status, created = LibraryStatus.objects.get_or_create(name="verfügbar")
            inst.status = current_status
            inst.save()
            return redirect(f"{reverse('inventory')}?filter_category=&filter_text={inst.inventory_number}")
        else:
            return render(request, 'library_new.html', {'form': f})

    default_status = LibraryStatus.objects.filter().last()
    f = InventoryItemForm(initial={'status': default_status})
    return render(request, 'library_new.html', {'form': f})


@login_required
@user_passes_test(is_library_admin)
def delete(request, id):
    obj = InventoryItem.objects.get(id=id)

    if request.method == 'POST':
        if request.POST.get('delete'):
            obj.delete()
        return redirect('inventory')

    return render(request, 'library_delete.html', {'obj': obj})


@login_required
@user_passes_test(is_library_admin)
def borrow(request, id):
    if request.method == 'POST':
        f = LibraryBorrowedItemsForm(request.POST)
        if f.is_valid():
            inst = f.save(commit=False)
            inventory_item = InventoryItem.objects.get(id=id)
            inst.book = inventory_item
            inst.borrowing_date = timezone.now()
            days = int(request.POST.get('days'))
            inst.return_date = timezone.now() + timezone.timedelta(days)
            inst.save()
            new_status, created = LibraryStatus.objects.get_or_create(name='entliehen')
            inventory_item.status = new_status
            inventory_item.save()
            return redirect('inventory')
        else:
            print(f.errors.as_text())

    f = LibraryBorrowedItemsForm()
    book = InventoryItem.objects.get(id=id)
    return render(request, 'library_borrow.html', {'form': f, 'book': book})


@login_required
@user_passes_test(is_library_admin)
def returnlist(request):
    borrowed_items = LibraryBorrowedItem.objects.all()
    return render(request, 'library_returnlist.html', {'borrowed_items': borrowed_items})


@login_required
@user_passes_test(is_library_admin)
def return_book(request, id):
    if request.method == 'POST':
        obj = LibraryBorrowedItem.objects.get(id=id)
        book = InventoryItem.objects.get(id=obj.book.id)
        new_status = LibraryStatus.objects.get(name='verfügbar')
        book.status = new_status
        book.save()
        obj.delete()
        return redirect('inventory')

    obj = LibraryBorrowedItem.objects.get(id=id)
    return render(request, 'library_return.html', {'obj': obj})


@login_required
@user_passes_test(is_library_admin)
def manage_categories(request):
    if request.method == 'POST':
        if request.POST.get('delete'):
            obj = LibraryCategoryShelfmark.objects.get(id=request.POST.get('delete'))
            obj.delete()
            return redirect('manage_categories')

    categories = LibraryCategoryShelfmark.objects.all()
    return render(request, 'library_categories.html', {'categories': categories})


@login_required
@user_passes_test(is_library_admin)
def new_category(request):
    if request.method == 'POST':
        f = LibraryCategoryShelfmarkNewForm(request.POST)
        if f.is_valid():
            f.save()
            return redirect('manage_categories')
        else:
            return render(request, 'library_new_category.html', {'form': f})

    f = LibraryCategoryShelfmarkNewForm()
    return render(request, 'library_new_category.html', {'form': f})


@login_required
@staff_member_required
def book_import(request):
    if request.method == 'POST':
        books = request.POST.get('books').split('\n')
        for book in books:
            i = book.split(';')
            obj_category_shelfmark, category_created = LibraryCategoryShelfmark.objects.get_or_create(category=i[2])
            if category_created:
                obj_category_shelfmark.shelfmark = i[3]
                obj_category_shelfmark.save()
            obj_location, created = LibraryLocation.objects.get_or_create(name=i[5].strip())
            obj_status, created = LibraryStatus.objects.get_or_create(name="verfügbar")
            InventoryItem.objects.create(
                author=i[0],
                title=i[1],
                category_shelfmark=obj_category_shelfmark,
                inventory_number=i[4],
                location=obj_location,
                status=obj_status
            )
        return redirect('inventory')

    return render(request, 'library_import.html', {})

library_manager/templates/library_base.html
<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Library-Manager</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-icons.min.css' %}">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <style>
      body {
        background-color: #ebebeb;
      }
    </style>
    <meta name="format-detection" content="telephone=no">
  </head>
  
  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
    <div class="container">
      {% load static %}
      <a class="navbar-brand btn btn-outline-secondary" href="/"><i class="bi bi-grid-3x3-gap-fill"> </i></a>
      <img src="{% static 'images/GNM.png' %}" width="40" class="ms-3"> <a class="navbar-brand ps-3 mb-0 h1" href="{% url 'inventory' %}">Library-Manager</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <form method="post" action="{% url 'logout' %}">
                {% csrf_token %}
               <button class="btn nav-link active" style="color: #0d6efd;"><strong><i class="bi bi-person-circle"></i> Logout ({{ user.username }})</strong></button>
              </form>
            </li>
            {% for group in user.groups.all %}
              {% if group.name == "teachers" %}
                <li class="nav-item">
                  <a class="nav-link {% if request.path == '/accounts/change_user/' %}active{% endif %}" href="/accounts/change_user/"><i class="bi bi-gear-fill"></i> Konto verwalten</a>
                </li>
              {% endif %}
            {% endfor %}
          {% endif %}
          {% if user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="/admin/">Django-Admin</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  </body>
</html>

library_manager/templates/library_borrow.html
{% extends 'library_base.html' %}
{% block content %}

<div class="card shadow bg-light mb-4">
  <div class="card-body">

    <div class="row">
      <div class="col">
        <h2>Ausleihe</h2>
      </div>
    <h5>Folgendes Buch</h5>

    <div class="alert alert-light">
      <small>
          <b></em>Autor:in:</b> {{ book.author }}</br>
          <b></em>Titel:</b> {{ book.title }}</br>
          <b></em>Signatur/Inventarnummer:</b> {{ book.category_shelfmark.shelfmark }}/{{ book.inventory_number }}
      </small>
    </div>

    <h5>wird verliehen an:</h5>

    <form method="post">
      {% csrf_token %}
        {{ form.as_p }}
        <div class="row mb-4">
          <label for="id_return">Rückgabe in:</label>
          <div class="col" id="id_return">
            <div class="form-check form-check-inline">
              <input class="form-check-input" type="radio" name="days" id="inlineRadio1" value="7" onclick="calculateDate()">
              <label class="form-check-label" for="inlineRadio1">1 Woche</label>
            </div>
            <div class="form-check form-check-inline">
              <input class="form-check-input" type="radio" name="days" id="inlineRadio2" value="14" onclick="calculateDate()">
              <label class="form-check-label" for="inlineRadio2">2 Wochen</label>
            </div>
            <div class="form-check form-check-inline">
              <input class="form-check-input" type="radio" name="days" id="inlineRadio3" value="21" onclick="calculateDate()" checked>
              <label class="form-check-label" for="inlineRadio3">3 Wochen</label>
            </div>
            <div class="form-check form-check-inline">
              <input class="form-check-input" type="radio" name="days" id="inlineRadio4" value="30" onclick="calculateDate()">
              <label class="form-check-label" for="inlineRadio4">4 Wochen</label>
            </div>
            <span class="badge rounded-pill text-bg-primary"><i class="bi bi-arrow-right-short"> </i><span id="futureDate"></span></span>
          </div>
        </div>
        <button name="save" class="btn btn-primary">Speichern</button>
        <a href="javascript:history.back()" class="btn btn-secondary">Abbrechen</a>
    </form>
  </div>
</div>

<script>
  calculateDate()
  function calculateDate() {
    // Get the selected radio button value
    const selectedOption = document.querySelector('input[name="days"]:checked').value;
    
    // Get the current date
    const currentDate = new Date();
    
    // Calculate the future date
    const futureDate = new Date(currentDate);
    futureDate.setDate(currentDate.getDate() + parseInt(selectedOption));

    // Format the future date (e.g., yyyy-mm-dd)
    const year = futureDate.getFullYear();
    const month = String(futureDate.getMonth() + 1).padStart(2, '0'); // Months are zero-based
    const day = String(futureDate.getDate()).padStart(2, '0');

    const formattedFutureDate = `${day}.${month}.${year}`;

    // Display the future date
    document.getElementById('futureDate').textContent = formattedFutureDate;
}
</script>

{% endblock content %}

library_manager/templates/library_delete.html
{% extends 'library_base.html' %}
{% block content %}

<div class="row">
  <div class="col">
    <h1>Buch löschen</h1>
  </div>
</div>

<form method="post">
  {% csrf_token %}
  <p>Soll dieser Datensatz wirklich <b>gelöscht werden?</b></p>
  <div class="alert alert-danger">
    <small>
        <p><b></em>Autor:in:</b> {{ obj.author }}</p>
        <p><b></em>Titel:</b> {{ obj.title }}</p>
        <p><b></em>Bereich/Signatur:</b> {{ obj.category_shelfmark }}</p>
        <p><b></em>Inventarnummer:</b> {{ obj.inventory_number }}</p>
    </small>
  </div>
  <button name="delete" value="True" class="btn btn-danger">Löschen</button>
  <a href="javascript:history.back()" class="btn btn-secondary">Abbrechen</a >
</form>

{% endblock content %}

library_manager/templates/library_inventory.html
{% extends 'library_base.html' %}
{% block content %}
<style>
  td {
    vertical-align: middle;
  }
</style>

<div class="card shadow bg-light mb-4">
  <div class="card-body mb-2">

    {% if not locations %}
      <div class="alert alert-danger">
        Der Administrator muss zunächst eine Bibliothek hinzufügen und einen oder mehrere Bibliothekverwalter über die Gruppenzugehörigkeit zur Gruppe 'library_admin' bestimmen.
      </div>
    {% endif %}

    <form class="mt-2">
      <div class="hstack gap-3">
          <label for="id_location" class="form-label mt-2">Bibliothek:</label>
        <div class="col-auto">
          <select name="location" class="form-select" id="id_location" onchange="this.form.submit()">
          {% for location in locations %}
            {% if current_location == location.id %}
              <option value="{{ location.id }}" selected>{{ location }}</option>
            {% else %}
              <option value="{{ location.id }}">{{ location }}</option>
            {% endif %}
          {% endfor %}
          </select>
        </div>
          <a class="btn btn-outline-dark {% if not library_admin %} disabled {% endif %}" href="{% url 'new' %}?location={{ current_location }}"><i class="bi bi-plus-square"></i> Buch hinzufügen</a>
          <div class="vr"></div>
          <a class="btn btn-outline-dark {% if not library_admin %} disabled {% endif %}" href="{% url 'manage_categories' %}?location={{ current_location }}"><i class="bi bi-tags"></i> Bereiche verwalten</a>
          <div class="vr"></div>
          <a class="btn btn-info {% if not library_admin %} disabled {% endif %}" href="{% url 'returnlist' %}?location={{ current_location }}"><i class="bi bi-card-checklist"></i> Rückgabeliste anzeigen</a>
      </div>

      <hr class="mt-4 mb-4">

      <div class="row">
        <div class="col">
          <label for="id_filter_category" class="form-label">Filter Bereich/Signatur</label>
          <select name="filter_category" class="form-select" id="id_filter_category" onchange="this.form.submit()">
            <option value="0">---</option>
            {% for category in category_items %}
              {% if current_category == category.id %}
                <option value="{{ category.id }}" selected>{{ category.category }} / {{ category.shelfmark }}</option>
              {% else %}
                <option value="{{ category.id }}">{{ category.category }} / {{ category.shelfmark }}</option>
              {% endif %}
            {% endfor %}
          </select>
        </div>
        <div class="col">
          <label for="id_filter_status" class="form-label">Filter Status</label>
          <select name="filter_status" class="form-select" id="id_filter_status" onchange="this.form.submit()">
            <option value="0">---</option>
            {% for status in status_items %}
              {% if current_status == status.id %}
                <option value="{{ status.id }}" selected>{{ status.name }}</option>
              {% else %}
                <option value="{{ status.id }}">{{ status.name }}</option>
              {% endif %}
            {% endfor %}
          </select>
        </div>
      </div>

      <div class="row mt-3">
        <div class="col pe-0">
            <input type="search" name="filter_text" class="form-control" value="{{ current_text }}" placeholder="Suche nach Autor:in oder Titel oder Inventarnummer">
        </div>
        <div class="col-auto">
            <button class="btn btn-primary">Suchen</button>
            <a href="{% url 'inventory' %}?filter_text=&filter_category=&filter_status=" class="btn btn-secondary" name="reset" value="reset" data-bs-toggle="tooltip" data-bs-title="Filter und Suche zurücksetzen">X</a>
        </div>
      </div>
    </form>
  </div>
</div>

<div class="card shadow bg-light">
  <div class="card-body">

    <table class="table table-striped table-hover mt-1">
      <thead class="table-light">
        <th>Autor:in</th>
        <th>Titel</th>
        <th>Bereich</th>
        <th>Signatur/Inventarnummer</th>
        <th>Status</th>
        <th>Aktionen</th>
      </thead>
      <tbody>
        {% for item in library_items %}
        {% if library_admin %}
          <tr onclick="window.location.href='/library_manager/edit/{{ item.id }}?filter_category={{ current_category }}&filter_status={{ current_status  }}&filter_text={{ current_text }}'" style="cursor: pointer;">
        {% endif %}
          <td>{{ item.author }}</td>
          <td>{{ item.title }}</td>
          <td>{{ item.category_shelfmark.category }}</td>
          <td>{{ item.category_shelfmark.shelfmark }}/{{ item.inventory_number }}</td>
          {% if item.status.name == "verfügbar" %}
            <td><span class="badge rounded-pill text-bg-success">{{ item.status }}</span></td>
          {% elif item.status.name == "entliehen" %}
            {% if item.borrowed.return_overdue %}
              <td><span class="badge rounded-pill text-bg-danger">entliehen <br>{{ item.borrowed.return_overdue }} Tage überfällig</span></td>
            {% else %}
              <td><span class="badge rounded-pill text-bg-info">{{ item.status }} bis<br>{{ item.borrowed.return_date }}</span></td>
            {% endif %}
          {% elif item.status.name == "verschwunden" %}
            <td><span class="badge rounded-pill text-bg-dark">{{ item.status }}</span></td>
          {% endif %}
          <td class="text-nowrap">
              {% if item.status.name == 'entliehen' %}
                <a href="{% url 'return_book' item.borrowed.id %}" class="btn btn-info btn-sm me-4 {% if not library_admin %} disabled {% endif %}"><i class="bi bi-building-fill"></i><i class="bi bi-arrow-left-short"></i><i class="bi bi-book"></i></a>
              {% else %}
                <a href="{% url 'borrow' item.id %}" class="btn btn-success btn-sm me-4 {% if item.status.name == 'verschwunden' %}disabled{% endif %} {% if not library_admin %} disabled {% endif %}"><i class="bi bi-book"></i><i class="bi bi-arrow-right-short"></i><i class="bi bi-person-fill"></i></a>
              {% endif %}
              <a href="{% url 'delete' item.id %}" class="btn btn-danger btn-sm {% if not library_admin %} disabled {% endif %}"><i class="bi bi-trash3-fill"></i></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    {% if item_count %}
      <div class="text-center mb-4">
        <a href="{% url 'inventory' %}?filter_text={{ current_text }}&filter_category={{ current_category }}&show_all=1">Alle {{ item_count }} Datensätze anzeigen</a>
      </div>
    {% endif %}

  </div>
</div>
<script>
  const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
  const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
</script>

{% endblock content %}