devicelist/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('<str:room>/<str:date>/<int:std>/<int:entry_id>/', views.devicelist, name='devicelist'),
    path('all/', views.devicelist_all, name='devicelist_all'),
    path('deviceEntry/all/', views.devicelistEntryNew, name='deviceEntryNewAll'),
    path('deviceEntry/<str:room>/<str:date>/<int:std>/<int:entry_id>/', views.devicelistEntryNew, name='deviceEntryNew'),
    path('deviceEntry/<int:id>/<str:room>/<str:date>/<int:std>/<int:entry_id>/', views.devicelistEntry, name='deviceEntry'),
    path('deviceUsers/<str:room>/<str:date>/<str:dev>/', views.lastDeviceUsers, name='deviceusers'),
]

edutools_site/urls.py
from django.contrib import admin
from django.urls import path, include
from mkr import views
# from .settings import MEDIA_URL, MEDIA_ROOT
# from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('edutools_home.urls')),
    path('wlan-codes/', include('WLANCodesWebApp.urls')),
    path('wlan-codes/codeimport/', include('codeimport.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('booking/', include('buchungstool.urls')),
    path('userlist/', include('userlist.urls')),
    path('booking/devices/', include('devicelist.urls')),
    path('booking/settings/', include('buchungstool_settings.urls')),
    path('mkr/', include('mkr.urls')),
    path('qrcode_generator/', include('qrcode_generator.urls')),
    path('library_manager/', include('library_manager.urls')),
    path('appointment/', include('appointment.urls')),
    path('activity/', include('activity.urls')),
    path('educards/', include('eduCards.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('logo/<filename>', views.get_logo, name='get_logo'),
]

# urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

mkr/urls.py
from django.urls import path
from . import views
from .views import rate_limit_exceeded_view

urlpatterns = [
    path('', views.home, name='mkr_home'),
    path('karte/', views.karte, name='karte'),
    path('karte_bearbeiten/<int:id>', views.karte_bearbeiten, name='karte_bearbeiten'),
    path('download/<filename>', views.download, name='download'),
    path('lehrplanansicht', views.lehrplanansicht, name='lehrplanansicht'),
    path('images/<filename>', views.get_image, name='get_image'),
    path('rate-limit-exceeded/', rate_limit_exceeded_view, name='rate_limit_exceeded'),
]

devicelist/models.py
from django.db import models
from buchungstool.models import Room


class Device(models.Model):
    def get_next_number():
        """
        Returns the next integer value in the dataset.
        """
        devices = Device.objects.all()
        if devices.count() == 0:
            return 1
        else:
            return devices.aggregate(models.Max('position'))['position__max'] + 1
    device = models.CharField(max_length=30)
    dbname = models.CharField(max_length=10, blank=True, null=True)
    position = models.PositiveIntegerField(default=get_next_number)

    def __str__(self):
        return self.device

    class Meta:
        ordering = ['position']


class Status(models.Model):
    status = models.CharField(max_length=20)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.status

    class Meta:
        verbose_name_plural = "Status"


class DevicelistEntry(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    # device = models.CharField(max_length=10)
    device = models.ForeignKey(Device, on_delete=models.DO_NOTHING)
    datum = models.DateField()
    stunde = models.IntegerField()
    beschreibung = models.CharField(max_length=300)
    krzl = models.CharField(max_length=10)
    status = models.ForeignKey(Status, on_delete=models.DO_NOTHING, default=1)
    behoben = models.CharField(max_length=10, blank=True)

    class Meta:
        verbose_name_plural = "DevicelistEntries"

    @property
    def age(self):
        from datetime import date
        today = date.today()
        age = today - self.datum
        age = str(age).split('d')[0].strip()
        return age

devicelist/forms.py
from django.forms import ModelForm
from django import forms
from .models import DevicelistEntry


class DevicelistEntryForm(ModelForm):
    class Meta:
        model = DevicelistEntry
        fields = (
            'room',
            'device',
            'datum',
            'stunde',
            'beschreibung',
            'krzl'
        )
        widgets = {
            'room': forms.Select(attrs={'class': 'form-select'}),
            'device': forms.Select(attrs={'class': 'form-select'}),
            'datum': forms.TextInput(attrs={'type': 'date', 'class': 'form-control', 'style': "height: 38px;"}),
            'stunde': forms.NumberInput(attrs={'class': 'form-control', 'min': 1, 'max': 11}),
            'beschreibung': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'krzl': forms.TextInput(attrs={'class': 'form-control'})
        }


class DevicelistEntryFormLoggedIn(ModelForm):
    class Meta:
        model = DevicelistEntry
        fields = (
            'room',
            'device',
            'datum',
            'stunde',
            'beschreibung',
            'krzl',
            'status',
            'behoben'
        )
        widgets = {
            'room': forms.Select(attrs={'class': 'form-select'}),
            'device': forms.Select(attrs={'class': 'form-select'}),
            'datum': forms.TextInput(attrs={'type': 'date', 'class': 'form-control', 'style': "height: 38px;"}),
            'stunde': forms.NumberInput(attrs={'class': 'form-control', 'min': 1, 'max': 11}),
            'beschreibung': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'krzl': forms.TextInput(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-select'}),
            'behoben': forms.TextInput(attrs={'class': 'form-control'}),
        }

devicelist/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required, user_passes_test
from buchungstool.models import Booking, Room
from buchungstool_settings.models import Setting
from .models import DevicelistEntry, Device, Status
from accounts.models import UserProfile
from .forms import DevicelistEntryForm, DevicelistEntryFormLoggedIn
from django.core.mail import send_mail
from django.db.models import Q


def is_teacher(user):
    return user.is_staff or user.groups.filter(name='teachers').exists()


@login_required
@user_passes_test(is_teacher)
def devicelist(request, room, date, std, entry_id):
    devices = Device.objects.all()
    obj = DevicelistEntry.objects.filter(room__short_name=room)
    iPads_with_entry = []
    for i in obj:
        iPads_with_entry.append(i.device)
    context = {
        'room': room,
        'date': date,
        'std': std,
        'devices': devices,
        'iPads_with_entry': iPads_with_entry,
        'devicelist': obj,
        'entry_id': entry_id,
    }
    return render(request, 'devicelist.html', context)


@login_required
@user_passes_test(is_teacher)
def devicelist_all(request):
    if request.GET.get('filter_status') and request.GET.get('filter_status') != "alle":
        filter_status = request.GET.get('filter_status')
        obj = DevicelistEntry.objects.filter(status__status=filter_status).order_by('room', 'device')
    else:
        obj = DevicelistEntry.objects.all().order_by('room', 'device')
        filter_status = ""
    if request.GET.get('filter_room') and request.GET.get('filter_room') != "alle":
        filter_room = int(request.GET.get('filter_room'))
        obj = obj.filter(room__id=filter_room).order_by('room', 'device')
    else:
        filter_room = ""
    if request.GET.get('textfilter'):
        try:
            idfilter = int(request.GET.get('textfilter'))
        except ValueError:
            idfilter = None

        textfilter = request.GET.get('textfilter')
        obj = obj.filter(
            Q(beschreibung__icontains=textfilter) |
            Q(id=idfilter) |
            Q(room__short_name__icontains=textfilter) |
            Q(krzl__icontains=textfilter) |
            Q(room__room__icontains=textfilter)
        )
    if request.GET.get('sortdate'):
        sortdate = request.GET.get('sortdate')
        if sortdate == "asc":
            obj = obj.order_by('datum', 'stunde')
        else:
            obj = obj.order_by('-datum', '-stunde')
    else:
        obj = obj.order_by('-datum', '-stunde')

    status = Status.objects.all()
    options = []
    options.append('alle')
    for s in status:
        options.append(s.status)

    room_obj = Room.objects.all()
    rooms = []
    rooms.append('alle')
    for room in room_obj:
        rooms.append(room)

    if request.GET.get('textfilter'):
        textfilter = request.GET.get('textfilter')
    else:
        textfilter = ""

    if request.GET.get('sortdate'):
        sortdate = request.GET.get('sortdate')
    else:
        sortdate = ""

    context = {
        'devicelist': obj,
        'options': options,
        'rooms': rooms,
        'filter_status': filter_status,
        'filter_room': filter_room,
        'textfilter': textfilter,
        'sortdate': sortdate,
    }
    return render(request, 'devicelist_all.html', context)


@login_required
@user_passes_test(is_teacher)
def devicelistEntry(request, id, room, date, std, entry_id):
    obj = get_object_or_404(DevicelistEntry, id=id)
    if request.method == "GET":
        # Update -> load instance
        if request.user.is_staff:
            f = DevicelistEntryFormLoggedIn(instance=obj)
            krzl = f.instance.krzl
            userprofile = UserProfile.objects.filter(abbr=krzl).first()
            if userprofile:
                email = userprofile.email
            else:
                email = ""
        else:
            f = DevicelistEntryForm(instance=obj)
            email = ""
    if request.method == "POST":
        if request.POST.get('save'):
            if request.user.is_staff:
                f = DevicelistEntryFormLoggedIn(request.POST, instance=obj)
            else:
                f = DevicelistEntryForm(request.POST, instance=obj)
            if f.is_valid():
                koffer = get_object_or_404(Room, id=int(request.POST.get('room')))
                device = Device.objects.get(id=int(request.POST.get('device')))
                if request.user.is_staff:
                    status = Status.objects.get(id=int(request.POST.get('status')))
                else:
                    status = request.POST.get('status')
                f.save()
                if request.POST.get('behoben'):
                    bearbeitet_von = request.POST.get('behoben')
                else:
                    bearbeitet_von = ""
                mail_text = (
                    "ID: " + str(obj.id) + "\n" +
                    "Datum: " + request.POST.get('datum') + "\n" +
                    "Stunde: " + request.POST.get('stunde') + "\n" +
                    "Standort/Koffer: " + koffer.short_name + "\n" +
                    "Gerät: " + str(device) + "\n" +
                    "Kürzel: " + request.POST.get('krzl') + "\n" +
                    "Beschreibung: " + request.POST.get('beschreibung') + "\n" +
                    "Status: " + str(status) + "\n" +
                    "Bearbeitet von: " + bearbeitet_von
                )
                subject = f'Support Ticket {str(obj.id)} Update: {str(status)}'

                if request.POST.get('email_to_second'):
                    email_to_second = request.POST.get('email_to_second')
                else:
                    email_to_second = ""

                send_support_mail(subject, mail_text, email_to_second)

                if request.POST.get('devicelist_all') == "True":
                    return redirect(reverse('devicelist_all') + "?" + request.GET.urlencode())
                else:
                    return redirect('devicelist', room=room, date=date, std=std, entry_id=entry_id)

        elif request.POST.get('delete'):
            koffer = get_object_or_404(Room, id=int(request.POST.get('room')))
            device = Device.objects.get(id=int(request.POST.get('device')))
            status = request.POST.get('status')
            if request.user.is_staff:
                status = Status.objects.get(id=int(request.POST.get('status')))
            else:
                status = request.POST.get('status')
            mail_text = (
                    "Folgende Schaden- oder Problemmeldung wurde gelöscht:\n\n" +
                    "ID: " + str(obj.id) + "\n" +
                    "Datum: " + request.POST.get('datum') + "\n" +
                    "Stunde: " + request.POST.get('stunde') + "\n" +
                    "Standort/Koffer: " + koffer.short_name + "\n" +
                    "Gerät: " + str(device) + "\n" +
                    "Kürzel: " + request.POST.get('krzl') + "\n" +
                    "Beschreibung: " + request.POST.get('beschreibung') + "\n" +
                    "Status: " + str(status)
                )

            email_to_second = ""

            subject = f'Support Ticket {str(obj.id)} gelöscht'
            send_support_mail(subject, mail_text, email_to_second)
            obj.delete()
            # Return to devicelist_all if coming from there -> use url parameter
            if request.POST.get('devicelist_all'):
                return redirect('devicelist_all')
            else:
                return redirect('devicelist', room=obj.room, date=obj.datum, std=obj.stunde, entry_id=entry_id)
        else:
            return redirect('devicelist', room=obj.room, date=obj.datum, std=obj.stunde, entry_id=entry_id)

    context = {
        'room': room,
        'devicelist': f,
        'date': date,
        'std': std,
        'support_id': id,
        'email': email,
        'devicelist_all': request.GET.get('devicelist_all'),
    }

    return render(request, 'devicelistEntry.html', context)


@login_required
@user_passes_test(is_teacher)
def devicelistEntryNew(request, room=None, date=None, std=None, entry_id=None):
    # get room id to pass in for initial data
    if room:
        room_id = get_object_or_404(Room, short_name=room).id
    else:
        room_id = None
    if request.method == "GET":
        # new empty form
        if request.user.is_staff:
            f = DevicelistEntryFormLoggedIn(initial={'room': room_id, 'datum': date, 'stunde': std})
        else:
            f = DevicelistEntryForm(initial={'room': room_id, 'datum': date, 'stunde': std})
    if request.method == "POST":
        if request.POST.get('save'):
            if request.user.is_staff:
                f = DevicelistEntryFormLoggedIn(request.POST)
            else:
                f = DevicelistEntryForm(request.POST)
            if f.is_valid():
                koffer = get_object_or_404(Room, id=int(request.POST.get('room')))
                device = Device.objects.get(id=int(request.POST.get('device')))
                if request.user.is_staff:
                    status = Status.objects.get(id=int(request.POST.get('status')))
                else:
                    status = request.POST.get('status')
                obj = f.save()
                mail_text = (
                    "ID: " + str(obj.id) + "\n" +
                    "Datum: " + request.POST.get('datum') + "\n" +
                    "Stunde: " + request.POST.get('stunde') + "\n" +
                    "Standort/Koffer: " + koffer.short_name + "\n" +
                    "Gerät: " + str(device) + "\n" +
                    "Kürzel: " + request.POST.get('krzl') + "\n" +
                    "Beschreibung: " + request.POST.get('beschreibung') + "\n" +
                    "Status: " + str(status)
                )

                if request.POST.get('email_to_second'):

devicelist/templates/devicelist.html
{% extends 'buchungstool_base.html' %}
{% block content %}

<div class="container">
  <div class="card shadow bg-light">
    <div class="card-body">
      <h2 class="mb-3">Support Tickets {{ room }}</h2>

      <form action="{% url 'deviceEntryNew' room date std entry_id %}">
        <button type="submit" class="btn btn-primary"><strong>+</strong> neuer Eintrag</button>
      </form>

      {% for device in devices %}
        {% if device in iPads_with_entry %}
          <h5 class="mt-4"><strong><u>{{ device }}</u></strong></h5>
          <div class="row mb-4">
            <div class="col">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Datum</th>
                    <th scope="col">Stunde</th>
                    <th scope="col">Beschreibung</th>
                    <th scope="col">Krzl.</th>
                    <th scope="col">Status</th>
                    <th scope="col" class="text-end">Aktion</th>
                  </tr>
                </thead>
                <tbody>
                {% for devicelist_entry in devicelist %}
                  {% if devicelist_entry.device == device %}
                    <form action="{% url 'deviceEntry' devicelist_entry.id room date std entry_id %}">
                      <tr>
                        <td>{{ devicelist_entry.id }}</td>
                        <td>{{ devicelist_entry.datum }}</td>
                        <td>{{ devicelist_entry.stunde }}</td>
                        <td>{{ devicelist_entry.beschreibung }}</td>
                        <td>{{ devicelist_entry.krzl }}</td>
                        <td class="{{ devicelist_entry.status.color }}">{{ devicelist_entry.status }}</td>
                        <td>
                          <div class="text-end">
                            <span style="white-space: nowrap;">
                              <button type="submit" class="btn btn-secondary btn-sm"><i class="bi bi-pencil-fill">&ensp;</i>Ändern</button>
                              {% if devicelist_entry.device.dbname %}
                                <a href="{% url 'deviceusers' room date devicelist_entry.device.dbname %}" class="btn btn-secondary btn-sm"><i class="bi bi-people-fill">&ensp;</i>letzte Benutzer</a>
                              {% endif %}
                            </span>
                          </div>
                        </td>
                      </tr>
                    </form>
                  {% endif %}
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
</div>

{% endblock content %}

devicelist/templates/devicelistEntry.html
{% extends 'buchungstool_base.html' %}
{% block content %}

<div class="container">
  <div class="card shadow bg-light">
    <div class="card-body">
      <h2 class="mb-3">Support Ticket {% if support_id %}{{ support_id }}{% else %} erstellen {% endif %}</h2>

      <div class="row mb-4">
        <div class="col">
          <form method="POST" onsubmit="disableSubmitButton(event)">
          {% csrf_token %}
            <div class="row">
              <div class="col">
                <label class="mt-3" for="Koffer" class="form-label">Raum/Standort:</label>
                {{ devicelist.room }}
              </div>
              <div class="col">
                <label class="mt-3" for="Datum" class="form-label">Datum:</label>
                {{ devicelist.datum }}
              </div>
              <div class="col">
                <label class="mt-3" for="Stunde" class="form-label">Stunde:</label>
                {{ devicelist.stunde }}
              </div>
              <div class="col">
                <label class="mt-3" for="Gerät" class="form-label">Gerät:</label>
                {{ devicelist.device }}
              </div>
              <div class="col">
                <label class="mt-3" for="Krzl" class="form-label">Krzl:</label>
                {% if devicelist.krzl.value %}
                  {{ devicelist.krzl }}
                {% else %}
                  <input type="text" name="krzl" value="{{ user.userprofile.abbr }}" class="form-control" maxlength="10" required id="id_krzl">
                {% endif %}
              </div>
            </div>

            <label class="mt-3" for="Beschreibung" class="form-label">Beschreibung:</label>
            {{ devicelist.beschreibung }}

            <div class="col">
              <label class="mt-3" for="Status" class="form-label">Status (Admin):</label>
              {% if user.is_staff %}
                {{ devicelist.status }}
              {% else %}
                <input type="text" name="status" class="form-control" value="{{ devicelist.instance.status }}" readonly disabled>
              {% endif %}
            </div>
            <div class="col">
              <label class="mt-3" for="Behoben" class="form-label">Bearbeitet durch (Admin):</label>
              {% if user.is_staff %}
                {% if devicelist.behoben.value %}
                  {{ devicelist.behoben }}
                {% else %}
                  <input type="text" name="behoben" class="form-control" value="{{ user.username }}" maxlength="10" required id="id_behoben">
                {% endif %}
              {% else %}
                <input type="text" class="form-control" value="{{ devicelist.instance.behoben }}" readonly disabled>
              {% endif %}
            </div>

            {% if user.is_staff %}
              <div class="col">
                <label class="mt-3" for="email_to_second" class="form-label">Statusänderung außerdem an folgende E-Mail-Adresse senden:</label>
                <input class="form-control" id="email_to_second" name="email_to_second" value="{{ email }}">
              </div>
            {% endif %}

            <button type="submit" name="save" value="save" class="btn btn-primary mt-5">
              <i class="bi bi-save"></i> Speichern
            </button>
            <input type="hidden" name="devicelist_all" value="{{ devicelist_all }}" />
            <input type="hidden" name="entry_id" value="{{ entry_id }}" />

            {% if not nodelete %}
              <button type="submit" name="delete" value="delete" class="btn btn-danger mt-5">
                <i class="bi bi-trash3"></i> Löschen
              </button>
            {% endif %}

            <a href="javascript:history.back()" class="btn btn-secondary mt-5"><i class="bi bi-x-square"></i> Abbrechen</a>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
function disableSubmitButton(event) {
    const button = event.submitter; // The actual clicked submit button
    if (button) {
        button.style.pointerEvents = 'none';
        if (button.name === 'save') {
            button.innerHTML = '<span class="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span> Speichern...';
        } else if (button.name === 'delete') {
            button.innerHTML = '<span class="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span> Löschen...';
        }
    }
    return true; // allow normal form submission
}
</script>

{% endblock content %}

devicelist/templates/devicelist_all.html
{% extends 'buchungstool_base.html' %}
{% block content %}

<div class="container">
  <div class="card shadow bg-light">
    <div class="card-body">
      <h2 class="mb-3">Support Tickets</h2>
      <div class="alert alert-info">
        Hier kannst du für alle <b>Räume mit Rechner/Smartboard/Beamer</b> ein Support Ticket eröffnen, wenn dort etwas nicht funktioniert. Außerdem kannst du hier alle Support Tickets durchsuchen. 
        <b>Tickets zu den iPad-Koffern kannst du einfacher über deinen gebuchten Termin eintragen.</b>
      </div>

      <h5 class="mt-3">Filter:</h5>
      <form class="mb-3">
        <div class="row">
          <div class="col pe-0">
            <label for="filter_status">Status:</label>
            <select name="filter_status" class="form-select" id="filter_status" onchange="this.form.submit()">
              {% for option in options %}
              {% if option == filter_status %}
                <option value="{{ option }}" selected>{{ option }}</option>
              {% else %}
                <option value="{{ option }}">{{ option }}</option>
              {% endif %}
              {% endfor %}
            </select>
          </div>
          <div class="col">
            <label for="filter_room">Raum/Standort:</label>
            <select name="filter_room" class="form-select" id="filter_room" onchange="this.form.submit()">
              {% for room in rooms %}
                {% if room == "alle" %}
                  <option selected>{{ room }}</option>
                {% else %}
                  {% if room.id == filter_room %}
                    <option value="{{ room.id }}" selected>{{ room }}</option>
                  {% else %}
                    <option value="{{ room.id }}">{{ room }}</option>
                  {% endif %}
                {% endif %}
              {% endfor %}
            </select>
          </div>
        </div>
        <div class="row mt-2">
          <div class="col pe-0">
            <input type="search" class="form-control" name="textfilter" {% if textfilter %} value="{{ textfilter }}" {% endif %} placeholder="Suche nach Beschreibung, Raum/Standort, Kürzel oder ID">
          </div>
          <div class="col-auto">
            <input type="hidden" name="sortdate" value="{{ sortdate }}">
            <button type="submit" class="btn btn-primary"><i class="bi bi-search"></i> SUCHEN</button>
          </div>
        </div>
      </form>

      <!-- <div class="text-end"> -->
        <a href="{% url 'deviceEntryNewAll' %}" type="submit" class="btn btn-primary"><strong>+</strong> neuer Eintrag</a>
      <!-- </div> -->

      <div class="row mb-4">
        <div class="col">
          <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">ID</th>
                <th scope="col">Raum/Standort</th>
                <th scope="col">Gerät</th>
                {% if sortdate == "asc" %}
                  <th class="text-nowrap" scope="col">Datum <a href="{% url 'devicelist_all' %}?{{ request.GET.urlencode }}&sortdate=desc"><i class="bi bi-arrow-down-short"></i></th>
                {% else %}
                    <th class="text-nowrap" scope="col">Datum <a href="{% url 'devicelist_all' %}?{{ request.GET.urlencode }}&sortdate=asc"> <i class="bi bi-arrow-up-short"></i></th>
                {% endif %}
                <th scope="col">Stunde</th>
                <th scope="col">Beschreibung</th>
                <th scope="col">Krzl.</th>
                <th scope="col">Status</th>
                <th scope="col" class="text-end">Aktion</th>
              </tr>
            </thead>
            <tbody>

            
              {% for devicelist_entry in devicelist %}
                


                  <tr>
                    <td class="align-middle">{{ devicelist_entry.id }}</td>
                    <td class="align-middle">{{ devicelist_entry.room }}</td>
                    <td class="align-middle">{{ devicelist_entry.device }}</td>
                    <td class="align-middle">{{ devicelist_entry.datum }}</td>
                    <td class="align-middle">{{ devicelist_entry.stunde }}</td>
                    <td class="align-middle">{{ devicelist_entry.beschreibung }}</td>
                    <td class="align-middle">{{ devicelist_entry.krzl }}</td>
                    <td class="{{ devicelist_entry.status.color }} align-middle">{{ devicelist_entry.status }}</td>
                    <td class="align-middle">
                      <div class="text-end">
                        <!-- <a href="{% url 'deviceEntry' devicelist_entry.id devicelist_entry.room.short_name devicelist_entry.datum devicelist_entry.stunde devicelist_entry.id %}?devicelist_all=True&filter_status={{ filter_status }}&filter_room={{ filter_room }}&textfilter={{ textfilter }}" class="btn btn-secondary btn-sm mb-1"><i class="bi bi-pencil-fill"></i> Ändern</a> -->
                          <a href="{% url 'deviceEntry' devicelist_entry.id devicelist_entry.room.short_name devicelist_entry.datum devicelist_entry.stunde devicelist_entry.id %}?{{ request.GET.urlencode }}&devicelist_all=True" class="btn btn-secondary btn-sm"><i class="bi bi-pencil-fill"></i> Ändern</a>
                        {% if devicelist_entry.device.dbname %}
                          <span style="white-space: nowrap;">
                            <a href="{% url 'deviceusers' devicelist_entry.room.short_name devicelist_entry.datum devicelist_entry.device.dbname %}?devicelist_all=True" class="btn btn-secondary btn-sm"><i class="bi bi-people-fill"></i> letzte Benutzer</a>
                          </span>
                        {% endif %}
                      </div>
                    </td>
                  </tr>

              {% endfor %}
            
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

devicelist/templates/deviceusers.html
{% extends 'buchungstool_base.html' %}
{% block content %}

<div class="container">
  <div class="card shadow bg-light">
    <div class="card-body">
      <h2 class="mb-3">Geräteliste</h2>
      <h5 class="mb-3">Die letzten 10 Benutzer von Gerät <strong>{{ dev }}</strong> seit dem <strong>{{ seit_datum }}</strong>:</h5>
      <div class="row mb-4">
        <div class="col">
          <table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col">Datum</th>
                  <th scope="col">Stunde</th>
                  <th scope="col">Krzl.</th>
                  <th scope="col">{{ dev }}</th>
                </tr>
              </thead>
              <tbody>
              {% for i in devlist %}
                <tr>
                  <td>{{ i.datum }}</td>
                  <td>{{ i.stunde }}</td>
                  <td>{{ i.krzl }}</td>
                  <td>{{ i.dev }}</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}